enable_selector = true
selector = "dmenu-wl"

[[handlers]]
exec = "chromium %u"
regexes = ['(https://)?(.*\.)?atlassian\.net/*.']

[[handlers]]
exec = "chromium %u"
regexes = ['(https://)?(.*\.)?azure\.com/*.']

[[handlers]]
exec = "orca-slicer %u"
regexes = ['.+\.step']
